# Generated by Django 4.1.2 on 2023-01-06 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=50)),
                ("content", models.TextField()),
                ("create_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={"db_table": "message",},
        ),
    ]
