# Generated by Django 4.1.2 on 2023-01-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("price", models.IntegerField()),
                ("genre", models.CharField(max_length=100)),
                ("photo", models.CharField(max_length=255)),
                ("url", models.CharField(max_length=255)),
                ("create_date", models.DateField(auto_now_add=True)),
            ],
            options={"db_table": "product",},
        ),
    ]
